name: Release

on:
  schedule:
    - cron: '0 10 */5 * *'
  release:
    types: [created]

env:
  REGISTRY_HOSTNAME: globalhealthmonitor
  IMAGE_NAME: ibmcloud-cli

jobs:
  build:
    name: Build Image and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: globalhealthmonitor/ibmcloud-cli:latest

      # - name: Push to GitHub Packages
      #   uses: docker/build-push-action@v2
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: docker.pkg.github.com
      #     repository: globalhealthmonitor/docker-ibmcloud-cli:latest
      #     push: true
